name: Tag release

on:
  workflow_dispatch:
    inputs:
      mescomptes:
        description: "Tag 'Mes Comptes' App"
        required: true
        type: boolean
        default: true
      hellobank:
        description: "Tag 'Hello Bank!' App"
        required: true
        type: boolean
        default: true
      delete_remote_branch:
        description: "Delete remote branch"
        required: false
        type: boolean
        default: false
      sha1:
        description: "Exact sha1 to tag (defaults to branch's HEAD)"
        required: false
        type: string
      message:
        description: "Quick release info used in tag message (append after branch name)"
        required: false
        type: string

jobs:
   tag:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: 📌 Tag repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          ./tag_release.sh "${{ inputs.mescomptes }}" "${{ inputs.hellobank }}" "${{ inputs.delete_remote_branch }}" "${{ inputs.sha1 }}" "${{ inputs.message }}"
